package com.sugarcrm.sugarcrm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.2
 * Tue May 11 13:08:09 CEST 2010
 * Generated source version: 2.1.2
 * 
 */
 
@WebService(targetNamespace = "http://www.sugarcrm.com/sugarcrm", name = "sugarsoapPortType")
@XmlSeeAlso({ObjectFactory.class,org.xmlsoap.schemas.soap.encoding.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SugarsoapPortType {

    @WebResult(name = "set_note_attachmentResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(operationName = "set_note_attachment", action = "http://localhost/sugar/service/v2/soap.php/set_note_attachment")
    public SetNoteAttachmentResponseType setNoteAttachment(
        @WebParam(partName = "parameters", name = "set_note_attachment", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        SetNoteAttachmentRequestType parameters
    );

    @WebResult(name = "logoutResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(action = "http://localhost/sugar/service/v2/soap.php/logout")
    public LogoutResponseType logout(
        @WebParam(partName = "parameters", name = "logout", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        LogoutRequestType parameters
    );

    @WebResult(name = "get_user_idResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(operationName = "get_user_id", action = "http://localhost/sugar/service/v2/soap.php/get_user_id")
    public GetUserIdResponseType getUserId(
        @WebParam(partName = "parameters", name = "get_user_id", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        GetUserIdRequestType parameters
    );

    @WebResult(name = "set_relationshipsResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(operationName = "set_relationships", action = "http://localhost/sugar/service/v2/soap.php/set_relationships")
    public SetRelationshipsResponseType setRelationships(
        @WebParam(partName = "parameters", name = "set_relationships", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        SetRelationshipsRequestType parameters
    );

    @WebResult(name = "set_entryResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(operationName = "set_entry", action = "http://localhost/sugar/service/v2/soap.php/set_entry")
    public SetEntryResponseType setEntry(
        @WebParam(partName = "parameters", name = "set_entry", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        SetEntryRequestType parameters
    );

    @WebResult(name = "get_available_modulesResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(operationName = "get_available_modules", action = "http://localhost/sugar/service/v2/soap.php/get_available_modules")
    public GetAvailableModulesResponseType getAvailableModules(
        @WebParam(partName = "parameters", name = "get_available_modules", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        GetAvailableModulesRequestType parameters
    );

    @WebResult(name = "loginResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(action = "http://localhost/sugar/service/v2/soap.php/login")
    public LoginResponseType login(
        @WebParam(partName = "parameters", name = "login", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        LoginRequestType parameters
    );

    @WebResult(name = "get_document_revisionResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(operationName = "get_document_revision", action = "http://localhost/sugar/service/v2/soap.php/get_document_revision")
    public GetDocumentRevisionResponseType getDocumentRevision(
        @WebParam(partName = "parameters", name = "get_document_revision", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        GetDocumentRevisionRequestType parameters
    );

    @WebResult(name = "get_user_team_idResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(operationName = "get_user_team_id", action = "http://localhost/sugar/service/v2/soap.php/get_user_team_id")
    public GetUserTeamIdResponseType getUserTeamId(
        @WebParam(partName = "parameters", name = "get_user_team_id", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        GetUserTeamIdRequestType parameters
    );

    @WebResult(name = "get_entries_countResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(operationName = "get_entries_count", action = "http://localhost/sugar/service/v2/soap.php/get_entries_count")
    public GetEntriesCountResponseType getEntriesCount(
        @WebParam(partName = "parameters", name = "get_entries_count", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        GetEntriesCountRequestType parameters
    );

    @WebResult(name = "get_module_fieldsResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(operationName = "get_module_fields", action = "http://localhost/sugar/service/v2/soap.php/get_module_fields")
    public GetModuleFieldsResponseType getModuleFields(
        @WebParam(partName = "parameters", name = "get_module_fields", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        GetModuleFieldsRequestType parameters
    );

    @WebResult(name = "set_relationshipResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(operationName = "set_relationship", action = "http://localhost/sugar/service/v2/soap.php/set_relationship")
    public SetRelationshipResponseType setRelationship(
        @WebParam(partName = "parameters", name = "set_relationship", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        SetRelationshipRequestType parameters
    );

    @WebResult(name = "set_campaign_mergeResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(operationName = "set_campaign_merge", action = "http://localhost/sugar/service/v2/soap.php/set_campaign_merge")
    public SetCampaignMergeResponseType setCampaignMerge(
        @WebParam(partName = "parameters", name = "set_campaign_merge", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        SetCampaignMergeRequestType parameters
    );

    @WebResult(name = "search_by_moduleResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(operationName = "search_by_module", action = "http://localhost/sugar/service/v2/soap.php/search_by_module")
    public SearchByModuleResponseType searchByModule(
        @WebParam(partName = "parameters", name = "search_by_module", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        SearchByModuleRequestType parameters
    );

    @WebResult(name = "get_server_infoResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(operationName = "get_server_info", action = "http://localhost/sugar/service/v2/soap.php/get_server_info")
    public GetServerInfoResponseType getServerInfo(
        @WebParam(partName = "parameters", name = "get_server_info", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        GetServerInfoRequestType parameters
    );

    @WebResult(name = "set_document_revisionResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(operationName = "set_document_revision", action = "http://localhost/sugar/service/v2/soap.php/set_document_revision")
    public SetDocumentRevisionResponseType setDocumentRevision(
        @WebParam(partName = "parameters", name = "set_document_revision", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        SetDocumentRevisionRequestType parameters
    );

    @WebResult(name = "set_entriesResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(operationName = "set_entries", action = "http://localhost/sugar/service/v2/soap.php/set_entries")
    public SetEntriesResponseType setEntries(
        @WebParam(partName = "parameters", name = "set_entries", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        SetEntriesRequestType parameters
    );

    @WebResult(name = "get_entry_listResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(operationName = "get_entry_list", action = "http://localhost/sugar/service/v2/soap.php/get_entry_list")
    public GetEntryListResponseType getEntryList(
        @WebParam(partName = "parameters", name = "get_entry_list", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        GetEntryListRequestType parameters
    );

    @WebResult(name = "get_relationshipsResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(operationName = "get_relationships", action = "http://localhost/sugar/service/v2/soap.php/get_relationships")
    public GetRelationshipsResponseType getRelationships(
        @WebParam(partName = "parameters", name = "get_relationships", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        GetRelationshipsRequestType parameters
    );

    @WebResult(name = "get_note_attachmentResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(operationName = "get_note_attachment", action = "http://localhost/sugar/service/v2/soap.php/get_note_attachment")
    public GetNoteAttachmentResponseType getNoteAttachment(
        @WebParam(partName = "parameters", name = "get_note_attachment", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        GetNoteAttachmentRequestType parameters
    );

    @WebResult(name = "get_entryResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(operationName = "get_entry", action = "http://localhost/sugar/service/v2/soap.php/get_entry")
    public GetEntryResponseType getEntry(
        @WebParam(partName = "parameters", name = "get_entry", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        GetEntryRequestType parameters
    );

    @WebResult(name = "get_entriesResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(operationName = "get_entries", action = "http://localhost/sugar/service/v2/soap.php/get_entries")
    public GetEntriesResponseType getEntries(
        @WebParam(partName = "parameters", name = "get_entries", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        GetEntriesRequestType parameters
    );

    @WebResult(name = "seamless_loginResponse", targetNamespace = "http://www.sugarcrm.com/sugarcrm", partName = "parameters")
    @WebMethod(operationName = "seamless_login", action = "http://localhost/sugar/service/v2/soap.php/seamless_login")
    public SeamlessLoginResponseType seamlessLogin(
        @WebParam(partName = "parameters", name = "seamless_login", targetNamespace = "http://www.sugarcrm.com/sugarcrm")
        SeamlessLoginRequestType parameters
    );
}
